[build]
target = 'x86_64-unknown-linux-gnu'
[target.aarch64-linux-android]
linker = '/home/dai/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
rustflags = [
    '-L',
    '/home/dai/d/etude-androidapp-rust/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.armv7-linux-androideabi]
linker = '/home/dai/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang'
rustflags = [
    '-L',
    '/home/dai/d/etude-androidapp-rust/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.i686-linux-android]
linker = '/home/dai/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android24-clang'
rustflags = [
    '-L',
    '/home/dai/d/etude-androidapp-rust/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.x86_64-linux-android]
linker = '/home/dai/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang'
rustflags = [
    '-L',
    '/home/dai/d/etude-androidapp-rust/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]
